### ISSUE TITLE
App crashes in 0.5.0

### ISSUE THREAD

**Issue by brentcwilson** [allRisc/RefWatchPlus#21]
As you noticed, the app crashed with the 0.5.0 release. I'm not sure why it didn't crash for me during testing. At first I thought perhaps something had happened during the merge of all the PRs. As it turns out, the crash was related only to the "GPS Off" feature. All of the other feature additions worked fine.

Because you have reverted to 0.4.1, I'm not sure how best to contribute toward the fix. The solution is simple enough. In the setGPSOff function in AppData.mc, change:

`		if (val) {
			Position.enableLocationEvents(Position.LOCATION_DISABLE, callback);
		} else {
			Position.enableLocationEvents(Position.LOCATION_CONTINUOUS, callback);
		}`

to

`		if (val) {
			Position.enableLocationEvents(Position.LOCATION_DISABLE, null);
		} else {
			Position.enableLocationEvents(Position.LOCATION_CONTINUOUS, null);
		}`

(In addition, the line above that conditional that defines the callback can be removed.)

The fix works in all of my testing so far, both in the simulator and on my device. I have two soccer matches tomorrow night during which I will test the fix under "live" conditions. I am using the v050 branch in my fork of your repo: https://github.com/brentcwilson/RefWatchPlus/tree/v050

**Comment by allRisc** [comment]
I also didn't catch it in testing until I started simulating the device with real FIT data.

I will look into this fix tonight or tomorrow. Thanks.

**Comment by allRisc** [comment]
Used this fix on a run today without issue. So I am going to push the solution and close, releasing v0.5.1

**Comment by allRisc** [comment]
@brentcwilson I already pushed this fix, but wanted to double check you had not encountered any issues in your game

**Comment by brentcwilson** [comment]
The crashes are gone. Yay!

I did notice a separate issue, however. I have submitted a fix as PR #25 .
