### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by alfredopg11** [allRisc/RefWatchPlus#28]
Some suggestions here:

- [ ] Second hand for the clock before starting the match
- [ ] Match summary after finishing the match
- [ ] Possibility to discard the activity once finished
- [ ] In period length menu, intervals of 5 minutes
- [ ] Data field with running pace

**Comment by allRisc** [comment]
@alfredopg11 Thanks for the suggestions!
A second hand-timer on the main screen already exists: it is the colored GPS ring.
I am working on a match-summary update along side a major code base update. Hopefully out by the end of year
I will create issues for the other three

**Comment by allRisc** [comment]
Issue #29, Issue #30, Issue #31 created to individually track other suggestions.

**Comment by alfredopg11** [comment]
I meant a second hand timer writed on text, in order to start the match on time more precisely

**Comment by allRisc** [comment]
Ah, makes sense. Issue #32 created to track
